spring:
  application:
    name: autumnLeavesHackerton
  config:
    import: optional:file:dev.env[.properties]
  profiles:
    include: secret
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    logging.level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  jackson:
    property-naming-strategy: SNAKE_CASE
JWT:
  SECRET-KEY: ${JWT_KEY}
KAKAO:
  KEY:
    CLIENT-ID: ${CLIENT-ID}
  REDIRECT-URI: ${REDIRECT-URI}